name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: ⚠️ Breaking
    labels:
      - breaking
  - title: 🚀 Features
    labels:
      - feature
  - title: 🐛 Bug Fixes
    labels:
      - bug
  - title: 🧰 Maintenance
    labels:
      -  chore
change-title-escapes: '\<*_&'  # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - breaking
  minor:
    labels:
      - feature
  patch:
    labels:
      - bug
  default: patch
template: ''
