with-expecter: true
packages:
  github.com/codetent/crypta/gen/daemon/v1/daemonv1connect:
    config:
    interfaces:
      DaemonServiceClient:
        config:
  github.com/codetent/crypta/pkg/daemon:
    config:
    interfaces:
      SecretStore:
        config:
