with-expecter: true
packages:
  github.com/codetent/crypta/gen/secret/v1/secretv1connect:
    config:
    interfaces:
      SecretServiceClient:
        config:
  github.com/codetent/crypta/pkg/store:
    config:
    interfaces:
      SecretStore:
        config:
