volumes:
  workspace:

services:
  dev:
    image: codetent/crypta-dev:4dc85186fa8e3bf467b99ce7530047e2f5d8237b
    tty: true
    volumes:
      - workspace:/workspace

x-mutagen:
  sync:
    workspace:
      alpha: ".."
      beta: volume://workspace
