volumes:
  workspace:

services:
  dev:
    image: codetent/crypta-dev:578eeebbdcbfe7d99b0fe2dbedfadb37973e8bce
    tty: true
    volumes:
      - workspace:/workspace

x-mutagen:
  sync:
    workspace:
      alpha: ".."
      beta: volume://workspace
