# This workflow will build & test the component

name: build

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: codetent/crypta-dev:e88d3dcd9dfbad063168b987a345a2fbde4b500c
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: goreleaser --clean --snapshot
