# This workflow will build & test the component

name: build

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: codetent/crypta-dev:4dc85186fa8e3bf467b99ce7530047e2f5d8237b
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build binaries & run tests
        run: goreleaser --clean --snapshot
      - name: Build documentation
        working-directory: docs
        run: |
          npm ci --no-audit --no-fund
          npm run build
