name: Build and push dev image

on:
  workflow_dispatch:
    inputs:
      commit:
        description: Commit to build
        required: true

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ inputs.commit }}

    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v4
      with:
        context: docker
        dockerfile: docker/Dockerfile
        push: true
        tags: codetent/crypta-dev:${{ github.sha }}
