name: Generate release pull request

on:
  workflow_dispatch:

jobs:
  generate-pr:
    runs-on: ubuntu-latest
    container: codetent/crypta-dev:578eeebbdcbfe7d99b0fe2dbedfadb37973e8bce
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Batch and merge
      run: |
        changie batch auto
        changie merge
        echo RELEASE_VERSION=$(changie latest) >> $GITHUB_ENV
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        title: Release ${{ env.RELEASE_VERSION }}
        branch: release/${{ env.RELEASE_VERSION }}
        commit-message: prepare ${{ env.RELEASE_VERSION }} release notes
